# -- Main Menu --
[[main]]
  name = "소개"
  pageRef = "about"
  weight = 10

[[main]]
  name = "강연 · 문의"
  pageRef = "lectures"
  weight = 20

[[main]]
  name = "성경공부"
  pageRef = "bible-study"
  weight = 30

[[main]]
  name = "블로그"
  pageRef = "blog"
  weight = 40

# -- Footer Menu --
[[footer]]
  name = "블로그"
  pageRef = "blog"
  weight = 10

[[footer]]
  name = "문의"
  pageRef = "lectures"
  weight = 20
